### PR TITLE
Admin tests

### PR DESCRIPTION
**Pull request by Goose-Of-War**
> _Uses a middleware which allows you to work as an admin user directly without going through the tedious work of setting up sign in and stuff_

- Checks if the `/list-users` and `/edit-user` pages are rendered.
- Checks if the validator works fine in the patch route.
- Checks if the patch route prevents edits on existing credential use.
- Checks if user details are successfully edited in both cases, with and without a new password.

### CODE REVIEW

**Review by nishkalprakash — COMMENTED** [review]
How do i test these tests?

**Comment by Goose-Of-War** [comment]
> How do i test these tests?

`npm run mocha <file-path>` should run the test
`npm run mocha-all` runs them all parallelly

**Comment by Goose-Of-War** [comment]
Though it does not console log or anything, you'd just be able to see if the code works or not :/

**Comment by nishkalprakash** [comment]
I dont know how to interpret the log thats being printed.
```
D:\Downloads\DarKSkuLL\MASK-Event>npm run mocha-all             

> mask-event@0.2.0 mocha-all
> cross-env NODE_ENV=test mocha test/**.js --parallel --exit


Starting in mongoless mode.

  Tools.deepEquals
    ✔ should equate correctly
    ✔ should inequate correctly

  Tools.deepClone
    ✔ should create a clone
    ✔ should remove references

  Tools.fakeRandom
    ✔ should have seed variability
    ✔ should have different second values
    ✔ should maintain seed replication

  Tools.Levenshtein
    ✔ should work with indel
    ✔ should work with switch
    ✔ should show swap as two operations

  Tools.LevenshteinDamerau
    ✔ should work with indel
    ✔ should work with switch
    ✔ should work with swap

  Tools.shell
    ✔ should run successfully


  Server (maintenance):
    ✔ should have the right PARAMS object
    ✔ should render a "Server Under Maintenance" page
    ✔ should send a "Server Under Maintenance" response

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(res.response?.status === 503)

    at D:\Downloads\DarKSkuLL\MASK-Event\test\site-maintenance.js:23:4
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { 
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v18.12.1

  Server (mongoless):
    ✔ should have the right PARAMS object
    ✔ should render  (122ms)


  Server (auth):
    1) Should have the right PARAMS object
    2) Should render /login page
    3) Should render /signup page
    4) Should render /logout page

  Should prevent signup in case of invalid data
    5) Missing name
    6) Missing roll
    7) Invalid roll
    8) Invalid roll
    9) Missing phone
    10) Invalid phone
    11) Invalid phone
    12) Missing email
    13) Invalid email
    14) Missing username
    15) Invalid username
    16) Invalid username
    17) Invalid username
    18) Missing password
    19) Invalid password
    20) Invalid password
    21) Invalid password

  Should prevent signup for already existing unique fields
    22) Existing username
    23) Existing email
    24) Existing roll

  Should signup for a set of fresh credentials
    25) Using randomly generated credentials

  Should prevent login in case of missing data
    26) Blank Username
    27) Blank Password

  Should not login for invalid credentials
    28) Invalid Username
    29) Incorrect Password

  Should login to test user successfully
    30) With test user credentials
```

**Comment by nishkalprakash** [comment]
Rerunning
```
D:\Downloads\DarKSkuLL\MASK-Event>npm run mocha-all

> mask-event@0.2.0 mocha-all
> cross-env NODE_ENV=test mocha test/**.js --parallel --exit


Starting in mongoless mode.

  Tools.deepEquals
    ✔ should equate correctly
    ✔ should inequate correctly

  Tools.deepClone
    ✔ should create a clone
    ✔ should remove references

  Tools.fakeRandom
    ✔ should have seed variability
    ✔ should have different second values
    ✔ should maintain seed replication

  Tools.Levenshtein
    ✔ should work with indel
    ✔ should work with switch
    ✔ should show swap as two operations

  Tools.LevenshteinDamerau
    ✔ should work with indel
    ✔ should work with switch
    ✔ should work with swap

  Tools.shell
    ✔ should run successfully

Starting in mongoless mode.

  Server (maintenance):
    ✔ should have the right PARAMS object
    ✔ should render a "Server Under Maintenance" page
    ✔ should send a "Server Under Maintenance" response

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(res.response?.status === 503)

    at D:\Downloads\DarKSkuLL\MASK-Event\test\site-maintenance.js:23:4
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v18.12.1

  Server (mongoless):
    ✔ should have the right PARAMS object
    ✔ should render  (184ms)


  Server (auth):
    1) Should have the right PARAMS object
    2) Should render /login page
    3) Should render /signup page
    4) Should render /logout page

  Should prevent signup in case of invalid data
    5) Missing name
    6) Missing roll
    7) Invalid roll
    8) Invalid roll
    9) Missing phone
    10) Invalid phone
    11) Invalid phone
    12) Missing email
    13) Invalid email
    14) Missing username
    15) Invalid username
    16) Invalid username
    17) Invalid username
    18) Missing password
    19) Invalid password
    20) Invalid password
    21) Invalid password

  Should prevent signup for already existing unique fields
    22) Existing username
    23) Existing email
    24) Existing roll

  Should signup for a set of fresh credentials
    25) Using randomly generated credentials

  Should prevent login in case of missing data
    26) Blank Username
    27) Blank Password

  Should not login for invalid credentials
    28) Invalid Username
    29) Incorrect Password

  Should login to test user successfully
    30) With test user credentials
```

**Review by nishkalprakash — APPROVED** [review]
Looks fine ig

**Pull request merged**
